win32: Makefile add winfiled target + NOTPARALLEL
- the .NOTPARALLEL option just disable the "-j" option effect at the
  level of the Makefile to keep it sequential. The "-j" will be passed
  to sub-level Makefile
- the new target allow to quickly RE-build the client when all files
  have been already compiled once.
- A quick way to build the client :
  use "make win64=yes bat=no winfiled -j 4" to quickly build the client
- this is not 100% reliable, but very convenient for faster development
  of the client.
- run the command twice to be sure.
- for the build of the package does as usual, don't use "-j"

diff --git a/bacula/src/win32/Makefile b/bacula/src/win32/Makefile
--- a/bacula/src/win32/Makefile
+++ b/bacula/src/win32/Makefile
@@ -14,6 +14,9 @@
 #     built.
 #
 
+# ignore "make -j N" option at this level
+.NOTPARALLEL:
+
 ECHO_CMD=@
 
 WIN32_DIRS=lib filed filed/plugins console scripts stored
@@ -66,6 +69,14 @@ release64/bat.exe: is_depkgs_set
 	test -f release64/bat.exe
 
 bat64: release64/bat.exe
+
+# a target that quickly build windows bacula-fd.exe
+winfiled:
+	@for I in lib filed filed/plugins console; \
+	  do (cd $$I; echo "==>Entering directory `pwd`"; \
+	      $(MAKE) DESTDIR=$(DESTDIR)  || (echo ""; echo ""; echo "  ====== Error in `pwd` ======"; \
+	                    echo ""; echo ""; false ) || false) || exit 1; \
+	done
 
 full_win32_installer:
 	@if test -f Makefile.inc; then \
