build: Update configure.in.

diff --git a/bacula/autoconf/configure.in b/bacula/autoconf/configure.in
--- a/bacula/autoconf/configure.in
+++ b/bacula/autoconf/configure.in
@@ -3231,40 +3231,6 @@ AC_CHECK_LIB(pthread, pthread_create, PTHREAD_LIB="-lpthread",
 )
 
 dnl
-dnl Enable/Disable plugin support
-dnl
-
-dnl Docker Plugin
-support_docker=auto
-AC_ARG_ENABLE(docker-plugin,
-   AC_HELP_STRING([--disable-docker-plugin], [disable Docker plugin support @<:@default=auto@:>@]),
-   [
-      if test x$enableval = xyes; then
-         support_docker=yes
-      elif test x$enableval = xno; then
-         support_docker=disabled
-      fi
-   ]
-)
-if test x$support_docker = xyes -o x$support_docker = xauto; then
-   AC_CHECK_PROG(docker_bin, docker, yes, no, "/usr/bin/")
-   if test x$docker_bin = xyes; then
-      support_docker=yes
-      FD_PLUGIN_DIR="${FD_PLUGIN_DIR} src/plugins/fd/docker"
-   else
-      if test x$support_docker = xyes; then
-         echo " "
-         echo "You enabled a Docker Plugin build but 'docker' command not found."
-         echo " "
-         exit 1
-      fi
-      support_docker=no
-   fi
-fi
-
-AC_SUBST(FD_PLUGIN_DIR)
-
-dnl
 dnl Check for LDAP libraries
 dnl
 LDAP_LIBS=""
@@ -3321,6 +3287,40 @@ AC_ARG_WITH(ldap,
 AC_SUBST(LDAP_LDFLAGS)
 AC_SUBST(LDAP_INC)
 AC_SUBST(LDAP_LIBS)
+
+dnl
+dnl Enable/Disable plugin support
+dnl
+
+dnl Docker Plugin
+support_docker=auto
+AC_ARG_ENABLE(docker-plugin,
+   AC_HELP_STRING([--disable-docker-plugin], [disable Docker plugin support @<:@default=auto@:>@]),
+   [
+      if test x$enableval = xyes; then
+         support_docker=yes
+      elif test x$enableval = xno; then
+         support_docker=disabled
+      fi
+   ]
+)
+if test x$support_docker = xyes -o x$support_docker = xauto; then
+   AC_CHECK_PROG(docker_bin, docker, yes, no, "/usr/bin/")
+   if test x$docker_bin = xyes; then
+      support_docker=yes
+      FD_PLUGIN_DIR="${FD_PLUGIN_DIR} src/plugins/fd/docker"
+   else
+      if test x$support_docker = xyes; then
+         echo " "
+         echo "You enabled a Docker Plugin build but 'docker' command not found."
+         echo " "
+         exit 1
+      fi
+      support_docker=no
+   fi
+fi
+
+AC_SUBST(FD_PLUGIN_DIR)
 
 dnl
 dnl Bacula Pluggable Authentication Modules - Director Plugins
