Update catalog to version 1023

diff --git a/bacula/src/cats/update_postgresql_tables.in b/bacula/src/cats/update_postgresql_tables.in
--- a/bacula/src/cats/update_postgresql_tables.in
+++ b/bacula/src/cats/update_postgresql_tables.in
@@ -562,6 +562,24 @@ END-OF-DATA
     fi
 fi
 
+if [ "$DBVERSION" -eq 1022 ] ; then
+    if psql -f - -d ${db_name} $* <<END-OF-DATA
+begin;
+ALTER TABLE Object ADD COLUMN ObjectCategory text not null;
+create index object_category_idx on Object  (ObjectCategory);
+UPDATE Version SET VersionId=1023;
+commit;
+END-OF-DATA
+    then
+	echo "Update of Bacula PostgreSQL tables 1022 to 1023 succeeded."
+	getVersion
+    else
+	echo "Update of Bacula PostgreSQL tables 1022 to 1023 failed."
+	exit 1
+    fi
+fi
+
+
 #
 # For all versions, we need to create the Index on Media(PoolId/StorageId)
 # It may fail, but it's not a big problem
diff --git a/bacula/src/cats/update_sqlite3_tables.in b/bacula/src/cats/update_sqlite3_tables.in
--- a/bacula/src/cats/update_sqlite3_tables.in
+++ b/bacula/src/cats/update_sqlite3_tables.in
@@ -305,10 +305,27 @@ UPDATE Version SET VersionId=1022;
 commit;
 END-OF-DATA
     then
-	echo "Update of Bacula SQLite3 tables 1020 to 1021 succeeded."
+	echo "Update of Bacula SQLite3 tables 1021 to 1022 succeeded."
 	getVersion
     else
-	echo "Update of Bacula SQLite3 tables 1020 to 1021 failed."
+	echo "Update of Bacula SQLite3 tables 1021 to 1022 failed."
+	exit 1
+    fi
+fi
+
+if [ "$DBVERSION" -eq 1022 ] ; then
+    if sqlite3 -f - -d ${db_name} $* <<END-OF-DATA
+begin;
+ALTER TABLE Object ADD COLUMN ObjectCategory text not null;
+create index object_category_idx on Object  (ObjectCategory);
+UPDATE Version SET VersionId=1023;
+commit;
+END-OF-DATA
+    then
+	echo "Update of Bacula SQLite3 tables 1022 to 1023 succeeded."
+	getVersion
+    else
+	echo "Update of Bacula SQLite3 tables 1022 to 1023 failed."
 	exit 1
     fi
 fi
