catalog: update to ver 1024

diff --git a/bacula/src/cats/update_mysql_tables.in b/bacula/src/cats/update_mysql_tables.in
--- a/bacula/src/cats/update_mysql_tables.in
+++ b/bacula/src/cats/update_mysql_tables.in
@@ -523,4 +523,21 @@ END-OF-DATA
     fi
 fi
 
+if [ "$DBVERSION" -eq 1023 ] ; then
+    if mysql $* -f  <<END-OF-DATA
+USE ${db_name};
+ALTER TABLE Object ADD ObjectStatus BINARY(1) DEFAULT 'U';
+ALTER TABLE Object ADD ObjectCount  INTEGER UNSIGNED DEFAULT 1;
+create index object_status_idx on Object  (ObjectStatus);
+UPDATE Version SET VersionId=1024;
+END-OF-DATA
+    then
+        echo "Update of Bacula MySQL tables 1023 to 1024 succeeded."
+        getVersion
+    else
+        echo "Update of Bacula MySQL tables 1023 to 1024 failed."
+        exit 1
+    fi
+fi
+
 exit 0
diff --git a/bacula/src/cats/update_postgresql_tables.in b/bacula/src/cats/update_postgresql_tables.in
--- a/bacula/src/cats/update_postgresql_tables.in
+++ b/bacula/src/cats/update_postgresql_tables.in
@@ -586,6 +586,23 @@ END-OF-DATA
     fi
 fi
 
+if [ "$DBVERSION" -eq 1023 ] ; then
+    if psql -f - -d ${db_name} $* <<END-OF-DATA
+begin;
+ALTER TABLE Object ADD COLUMN ObjectStatus char(1) default 'U';
+ALTER TABLE Object ADD COLUMN ObjectCount integer default 1;
+create index object_status_idx on Object (ObjectStatus);
+UPDATE Version SET VersionId=1024;
+commit;
+END-OF-DATA
+    then
+	echo "Update of Bacula PostgreSQL tables 1023 to 1024 succeeded."
+	getVersion
+    else
+	echo "Update of Bacula PostgreSQL tables 1023 to 1024 failed."
+	exit 1
+    fi
+fi
 
 #
 # For all versions, we need to create the Index on Media(PoolId/StorageId)
